### ISSUE TITLE
Increase size limits

### ISSUE THREAD

**Issue by KellerFuchs** [hashbang/docker-slapd#3]
A few days ago, [`provisor`](https://github.com/hashbang/provisor) started running into a too-low reply size limit.

@lrvick told me how to fix this, and I did, but the fix should also be integrated in the setup script here.

**Comment by RyanSquared** [comment]
What was required to increase the size limit? Is there an existing pull request or some other thing?

**Comment by RyanSquared** [comment]
And, yeah, there's been several too-low limits. We've just been manually re-setting it.

**Comment by KellerFuchs** [comment]
Closed by #4
